<?php
/**
 * Copyright © element119. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;

/** @var Escaper $escaper */
/** @var AbstractBlock $block */

// We should use strlen function because coupon code could be "0", converted to bool will lead to false
$hasCouponCode = $block->getCouponCode() !== null && strlen($block->getCouponCode()) > 0;
?>
<div class="block discount"
     id="block-discount"
     data-mage-init='{
         "collapsible": {
             "active": <?= $hasCouponCode ? 'true' : 'false'; ?>,
             "openedState": "active",
             "saveState": false
         }
     }'>
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2">
            <?= $block->escapeHtml(__('Apply Discount Code')); ?>
        </strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <?= /** @noEscape */ $block->getChildHtml('magewire.coupon-code'); ?>
    </div>
</div>
